#!/bin/bash -e
# $File: genpot
# $Date: Tue Feb 14 16:10:26 2012 +0800
# $Author: jiakai <jia.kai66@gmail.com>

FOUT=pynojo/nls/pynojo.pot
cd ..
. ./init.sh


eval $(grep 'RELEASE =' pynojo/config/pkg.py | sed -e 's/ //g')

echo -n "Extracting from python source ..."
find pynojo -name "*.py" | \
	xgettext --copyright-holder 'pynojo development team' --package-name pynojo \
	--package-version "$RELEASE" --from-code=UTF-8 --keyword=_  \
	--keyword=_pl:1,2 -f - -o "$FOUT"

echo ' done'

echo >> "$FOUT"

pybabel extract \
	--no-default-keywords --omit-header \
	--keyword=_  --keyword=_pl:1,2 -F utils/babel.cfg \
	-o - . >> "$FOUT"

# vim: ft=sh
